language/move-core/types/Cargo.toml, language/move-core/types/src/abi.rs, language/move-core/types/src/account_address.rs, language/move-core/types/src/effects.rs, language/move-core/types/src/errmap.rs, language/move-core/types/src/gas_algebra.rs, language/move-core/types/src/identifier.rs, language/move-core/types/src/language_storage.rs, language/move-core/types/src/lib.rs, language/move-core/types/src/metadata.rs, language/move-core/types/src/move_resource.rs, language/move-core/types/src/parser.rs, language/move-core/types/src/resolver.rs, language/move-core/types/src/state.rs, language/move-core/types/src/transaction_argument.rs, language/move-core/types/src/u256.rs, language/move-core/types/src/value.rs, language/move-core/types/src/vm_status.rs
This updates only `move-core-types`, but not other crates that depend on `move-core-types`. That will be done in a separate PR. With this PR, the crate can be built with `wasm32-unknown-unknown` target and included in a Substrate pallet.
=> feat(move-core-types): add no-std support

language/move-binary-format/Cargo.toml, language/move-binary-format/src/access.rs, language/move-binary-format/src/binary_views.rs, language/move-binary-format/src/compatibility.rs, language/move-binary-format/src/constant.rs, language/move-binary-format/src/control_flow_graph.rs, language/move-binary-format/src/cursor.rs, language/move-binary-format/src/deserializer.rs, language/move-binary-format/src/errors.rs, language/move-binary-format/src/file_format.rs, language/move-binary-format/src/file_format_common.rs, language/move-binary-format/src/lib.rs, language/move-binary-format/src/normalized.rs, language/move-binary-format/src/proptest_types.rs, language/move-binary-format/src/proptest_types/constants.rs, language/move-binary-format/src/proptest_types/functions.rs, language/move-binary-format/src/proptest_types/metadata.rs, language/move-binary-format/src/proptest_types/signature.rs, language/move-binary-format/src/proptest_types/types.rs, language/move-binary-format/src/serializer.rs, language/move-binary-format/src/unit_tests/number_tests.rs, language/move-binary-format/src/unit_tests/signature_token_tests.rs, language/move-binary-format/src/views.rs
Two commits:
```
feat(move-binary-format): no-std adaptation
```
```
feat(move-binary-format): add custom Cursor impl
`std::io::Cursor` will need replacement in no-std env,
so a stripped-down version of it is needed.
```
=> feat(move-binary-format): no-std adaptation

Cargo.lock, language/move-binary-format/Cargo.toml, language/move-core/types/Cargo.toml, language/move-core/types/src/account_address.rs, language/move-core/types/src/errmap.rs, language/move-core/types/src/lib.rs, language/move-core/types/src/state.rs
With this PR, all tests are now passing in both `move-core-types` and `move-binary-format`.
Some commented parts of `move-core-types` are uncommented and feature-gated instead.
```
chore(move-core-types): fix tests
```
```
chore(move-core-types): gate files required for toolchain
Some files are not required for the pallet-move and no-std environment
```
=>     chore(move-core-types): fix tests

Cargo.lock, language/move-core/types/Cargo.toml, language/move-vm/types/Cargo.toml, language/move-vm/types/src/data_store.rs, language/move-vm/types/src/lib.rs, language/move-vm/types/src/loaded_data/runtime_types.rs, language/move-vm/types/src/values/value_tests.rs, language/move-vm/types/src/values/values_impl.rs, language/move-vm/types/src/views.rs
no_std support has been added to the `move-vm-types` package.
The crate can now be compiled inside the WASM environment.
All tests are passing.
=> feat: make move-vm-types package no_std compatible

language/move-binary-format/src/errors.rs, language/move-core/types/src/account_address.rs, language/move-core/types/src/errmap.rs, language/move-core/types/src/u256.rs, language/move-core/types/src/vm_status.rs, language/move-stdlib/Cargo.toml
`move-cli`, `move-disassembler` can be compiled again.
The tests for `move-cli` are still failing, though. That'll be addressed in a separate PR.
=> chore: fixes for move-cli

.github/workflows/check-move-packages-pull-request.yml, .github/workflows/check-move-packages-push.yml
Updates:
- run full test suite when a commit is merged.
- skip running `move-compiler` tests on pull_request action.
=> ci: run tests on push action

language/move-bytecode-verifier/Cargo.toml
Use the forked petgraph repo which is no-std compatible.
=> deps: update petgraph to use no-std

Cargo.lock, language/extensions/move-table-extension/Cargo.toml, language/move-vm/runtime/Cargo.toml, language/tools/move-unit-test/Cargo.toml
`better_any` crate doesn't provide no-std support, so use our own forked version of `better_any`.
=> deps: use no-std better_any fork

Cargo.lock, language/move-vm/runtime/Cargo.toml, move-vm-backend/Cargo.toml, move-vm-backend/src/lib.rs, move-vm-backend/src/storage.rs, move-vm-backend/tests/assets/move/Move.toml, move-vm-backend/tests/assets/move/scripts/empty.move, move-vm-backend/tests/assets/move/sources/Empty.move, move-vm-backend/tests/assets/move/sources/Full.move, move-vm-backend/tests/mock.rs, move-vm-backend/tests/move_vm.rs
This PR gives the ability to run Move Virtual Machine inside the `move-vm-backend` crate, add storage and test if publishing modules work as expected. It also gives the ability to call publishing from the outer world like `pallet-move` and the real Substrate node.
Commits will be squashed.
=> feat: running VM with publishing modules feature

move-vm-backend/src/storage.rs, move-vm-backend/tests/move_vm.rs
This changes using a serialized ModuleId structure to access modules by calling the MoveResolver trait function. From now on, we are using only AccountAddress to get, set and remove items in the storage.
=> chore: use AccountAddress to access storage instead of serialized ModuleId

move-vm-backend/tests/move_vm.rs
Checking if the operation returned Ok() is not enough for those two functions because they return Ok(None) in case of not finding module/resource.
For get_module test: added assert to check if bytecode received from the get_module call is the same which was uploaded previously using publish_module. Works fine.
For get_resource test: added a simple check if the returned value contains something, so whether we won't fall to Ok(None) case.
Unfortunately, this test fails now.
=> test: additional checks for get_module and get_resource

move-vm-backend/tests/assets/move-projects/basic_coin/Move.toml, move-vm-backend/tests/assets/move-projects/basic_coin/sources/BasicCoin.move, move-vm-backend/tests/move_vm.rs
BasicCoin Move contract added to be used with get_resource test.
Introduced `read_stdlib_module_bytes_from_project` temporary call for loading parts of Stdlib that are needed to run our product.
The call can be removed when Move Stdlib is loaded with genesis initialization.
=> test: basic coin Move contract added to be used with get_resource test

language/documentation/examples/diem-framework/crates/cli/src/main.rs, language/tools/move-cli/src/lib.rs
The update is necessary to make the smove implementation less complex
=> chore: move-cli update

.github/workflows/check-move-backend-pull-request.yml, move-vm-backend/src/lib.rs, move-vm-backend/tests/move_vm.rs
Also
- includes `move-vm-backend-common` in the CI
- fixes broken `move-vm-backend` after a recent renaming change
=> chore: a new test for the `smove-bundle` command

Cargo.lock, Cargo.toml, language/move-compiler/Cargo.toml, language/move-compiler/src/parser/lexer.rs, move-vm-support/Cargo.toml, move-vm-support/src/lib.rs, move-vm-support/src/ss58_address.rs
Library with support and helper functions for using MoveVM in Substrate-based chains.
Initial commit with SS58 to Move address conversion.
=> feat: move-vm-support library with SS58 to Move address conversion

move-vm-backend/src/lib.rs, move-vm-backend/tests/move_vm.rs
New, more user-friendly API for communication with the pallet. 
Now, we don't need to expose the `Identifier` and `ModuleId` types to the upper layer.
=> feat: change API for get_module(_abi) to pass not serialized parameters

language/move-vm/runtime/Cargo.toml, language/move-vm/runtime/src/interpreter.rs, language/move-vm/runtime/src/lib.rs
* featuregated `trace` with `debugging` feature;
* fixed `debuigging` feature to use `std` feature and build in `no-std` or --no-default-features;
=> build(features): debugging feature build fix in no-default-features

.github/actions/build-setup/action.yml, .github/workflows/check-move-backend-pull-request.yml, README.md, move-vm-backend/Cargo.toml, move-vm-backend/build.rs, move-vm-backend/tests/assets/move-projects/smove-build-all.sh, move-vm-backend/tests/move_vm.rs
- [feat(move-vm-backend): add script for building move projects](https://github.com/eigerco/substrate-move/commit/ffcf7f123836680ebb06b190424578d6f76c6fbf)
Added a new feature which can be used to compile all the necessary move
projects in the tests/assets/move-projects/ directory.
Running:
```
cargo test -p move-vm-backend --features build-move-projects-for-test
```
will always succeed (the only requirement is to have smove installed).
- [doc(readme): first version of the doc](https://github.com/eigerco/substrate-move/commit/94c20588dce30df4ce91584186d22fa67448489b)
- [ci: get smove in order to use it in the CI](https://github.com/eigerco/substrate-move/commit/093f091d16e18f6e679b4ca10a595121e9e97ec7)
- updated the instructions for running move-vm-backend tests with a
feature flag to …
=> Build solution for the smove tool which can be used to run tests in the CI

language/move-stdlib/Move.toml, language/move-stdlib/build.rs, language/move-stdlib/nursery/Move.toml, language/move-stdlib/src/lib.rs, language/tools/move-cli/tests/move_unit_tests/assign_dev_addr_for_dep/Move.toml, language/tools/move-cli/tests/move_unit_tests/standalone_module_with_dev_addr_assignment/Move.toml, language/tools/move-cli/tests/move_unit_tests/standalone_module_with_regular_addr_assignment/Move.toml, move-vm-backend/tests/move_vm.rs
In order to initialize the move-vm-backend, we'll need to provide a precompiled stdlib bundle.
The `smove` tool is used to compile all Move stdlib source files into a bundle before the actual compilation of the move-stdlib package even begins.
EDIT:
~_This PR can't be merged yet because we need to make sure the `smove` tool can be used in the CI files first._~
[Dependent PR](https://github.com/eigerco/substrate-move/pull/46) has been merged which makes it possible to use `smove` in GA workflow.
=> feat: precompile stdlib bundle

language/move-stdlib/Cargo.toml, language/move-stdlib/build.rs, language/move-stdlib/src/lib.rs, move-vm-backend/Cargo.toml, move-vm-backend/tests/move_vm.rs
Since `smove` depends on `move-stdlib`, and then `move-stdlib` needs to use `smove` to compile the bundle - we need to break that cyclic dependency.
This is done with a new feature called `stdlib-bytecode`.
So if any crates need a compiled stdlib bytecode (e.g. `move-vm-backend`), they'll get it by enabling this feature.
=> fix(stdlib): feature for stdlib bytecode

Cargo.lock, move-vm-backend-common/Cargo.toml, move-vm-backend-common/src/gas_schedule.rs, move-vm-backend-common/src/lib.rs
Includes a new `gas_schedule` module under `move-vm-backend-common`, which contains all the gas cost handling, both for instructions and also for native functions.
This module shall be used by:
- `smove`
- `move-vm-backend`
=> feat: basic gas cost table

.github/workflows/check-move-backend-pull-request.yml, move-vm-backend/Cargo.toml, move-vm-backend/build.rs, move-vm-backend/src/lib.rs, move-vm-backend/src/types.rs, move-vm-backend/src/warehouse.rs, move-vm-backend/tests/mock.rs, move-vm-backend/tests/move_vm.rs
Use a custom gas strategy:
- backend API updated to use GasStrategy enum
- use a custom gas table/strategy provided by the `move-vm-backend-common`
- a new test written with a metered gas
Small extra changes:
- removed unused imports
- removed some bits that will never be used
- again using the `build-move-projects-for-test feature` since:
- it's speeds up the build
- constantly compiling the same Move packages (in `tests/assets`) somehow
messes up the cache in `~/.move`. So, not compiling those
packages on every run help a lot.
=> feat: apply custom gas strategy 

Cargo.lock, language/move-vm/test-utils/Cargo.toml, language/move-vm/test-utils/src/gas_schedule.rs, language/move-vm/test-utils/src/lib.rs, language/move-vm/test-utils/src/storage.rs, move-vm-backend-common/src/gas_schedule.rs, move-vm-backend/Cargo.toml, move-vm-backend/tests/move_vm.rs
A quick one - we need to ensure `move-vm-test-utils` which is now included in `move-vm-backend` is also no-std compatible.
=> feat(no-std): adapt move-vm-test-utils

move-vm-backend-common/src/types.rs, move-vm-backend/src/lib.rs, move-vm-backend/tests/move_vm.rs
So, for a set of modules, we'll use the term bundle instead of package (which can interfere with a `Module Package` term)
- another tiny change here: start using an already prepared STD address from `move_core_types` in tests
=> chore: rename module package to bundle

move-vm-backend-common/src/gas_schedule.rs, move-vm-backend/src/lib.rs, move-vm-backend/src/types.rs, move-vm-backend/tests/move_vm.rs
It's a very simple implementation for now.
The current value of 100 gas is charged per published byte.
This value should be tweaked in the future.
=> feat: charge gas for publishing

language/move-stdlib/.gitignore, language/move-stdlib/build.rs, language/move-stdlib/build_stdlid_with_smove.sh, language/move-stdlib/src/lib.rs, move-vm-backend/src/genesis.rs, move-vm-backend/tests/mock.rs, move-vm-backend/tests/move_vm.rs
- inclusion of substrate-stdlib bytecode in the move-stdlib crate.
- genesis configuration updated with substrate-stdlib support.
- tests for genesis configuration.
=> feat: add substrate-stdlib support

language/move-stdlib/src/natives/balance.rs, language/move-stdlib/src/natives/mod.rs, language/move-vm/types/src/values/values_impl.rs, move-vm-backend-common/src/gas_schedule.rs, move-vm-backend/src/genesis.rs, move-vm-backend/tests/assets/move-projects/smove-build-all.sh, move-vm-backend/tests/assets/move-projects/substrate_balance/Move.toml, move-vm-backend/tests/assets/move-projects/substrate_balance/sources/Transfer.move, move-vm-backend/tests/move_vm.rs
- Basic native function support for substrate-stdlib::balance module
which allows functions to be called inside Move scripts.
- test: add substrate-stdlib balance module basic tests
=> feat: native function suport for balance module 

language/move-core/types/src/resolver.rs, language/move-stdlib/src/natives/balance.rs, language/move-vm/integration-tests/src/tests/bad_storage_tests.rs, language/move-vm/runtime/src/data_cache.rs, language/move-vm/runtime/src/native_functions.rs, language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs, language/move-vm/test-utils/src/storage.rs, language/move-vm/types/src/data_store.rs, language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs, move-vm-backend/src/warehouse.rs, move-vm-backend/tests/assets/move-projects/substrate_balance/sources/Transfer.move
Integrate a `BalanceResolver` into the MoveVM so native functions inside the balance module under the substrate-stdlib could perform cheque updates to the external balance handler.
=> feat: add balance resolver

.github/workflows/check-move-packages-pull-request.yml, Cargo.lock, language/move-core/types/Cargo.toml, language/move-core/types/src/account_address.rs, language/move-core/types/src/identifier.rs, language/move-core/types/src/language_storage.rs, move-vm-backend-common/Cargo.toml, move-vm-backend-common/src/abi.rs, move-vm-backend-common/src/lib.rs, move-vm-backend/Cargo.toml, move-vm-backend/src/lib.rs
- make move-vm-backend::abi decodable for substrate
- move move-vm-backend::abi to move-vm-backend-common
- unify used crate versions in manifest files
- restore commented code for later usage
=> feat: make module abi decodable in substrate

language/move-core/types/src/resolver.rs, language/move-core/types/src/vm_status.rs, language/move-vm/integration-tests/src/tests/bad_storage_tests.rs, language/move-vm/runtime/src/data_cache.rs, language/move-vm/runtime/src/unit_tests/vm_arguments_tests.rs, language/move-vm/test-utils/src/storage.rs, language/tools/move-cli/src/sandbox/utils/on_disk_state_view.rs, move-vm-backend/src/balance.rs, move-vm-backend/src/genesis.rs, move-vm-backend/src/lib.rs, move-vm-backend/src/warehouse.rs, move-vm-backend/tests/assets/move-projects/substrate_balance/sources/Transfer.move, move-vm-backend/tests/mock.rs, move-vm-backend/tests/move_vm.rs
Balance trait can be used to inject an external balance handler inside the MoveVM.
_reusing a testing PR that was accidentally published in this repo, sorry for a strange branch name..._
=> feat: add balance trait for the substrate layer 

move-vm-backend-common/src/types.rs
- This will be used by the `pallet-move` and the `smove` and possibly by the `move-vm-backend`.
So this is the [current location](https://github.com/eigerco/pallet-move/blob/main/src/transaction.rs) for this type, and we are going to remove it from there in the next pallet-move PR.
=> chore: use backend-common for `ScriptTransaction`

README.md, move-vm-backend/src/genesis.rs, move-vm-support/src/ss58_address.rs
This PR also fixes two small warnings in our backend packages.
=> doc: restructuring readme

language/move-vm/types/src/views.rs
- move-vm-runtime depends on move-vm-types and both are used in the no-std environment within the pallets runtime.
=> chore(move-vm-types): ensure no-std compatibility

language/move-stdlib/build_stdlid_with_smove.sh, language/move-stdlib/src/lib.rs, language/tools/move-cli/src/sandbox/commands/test.rs, move-vm-backend/tests/assets/move-projects/substrate_balance/Move.toml
- harmonise naming style of Move-stdlibs, here: `SubstrateStdlib`
- Note: There is one minor `cargo fmt` correction that has been added - too small for a separate PR :blush:
=> chore: harmonise naming style in Move stdlibs

move-vm-support/src/base58_address.rs, move-vm-support/src/lib.rs, move-vm-support/src/ss58_address.rs
- new module for base58 address string encoding and decoding
- module includes methods to convert from and to ss58 address format
=> feat: add base58 support to move-vm-support

language/move-command-line-common/src/address.rs, language/move-command-line-common/src/parser.rs, language/tools/move-package/src/source_package/manifest_parser.rs, move-vm-backend/tests/assets/move-projects/base58_smove_build/Move.toml, move-vm-backend/tests/assets/move-projects/base58_smove_build/sources/BobBase58.move, move-vm-backend/tests/assets/move-projects/smove-build-all.sh, move-vm-support/src/base58_address.rs
- integrate base58 encoding functionality into `move-command-line-common` and `move-package`
=> feat: integrate base58 encoding support into substrate-move

move-vm-backend-common/src/gas_schedule.rs, move-vm-backend/src/types.rs, move-vm-backend/tests/move_vm.rs
- renamed constant to `MILLIGAS_COST_PER_PUBLISHED_BYTE`
- increased constant by factor 10 after evaluation of gas costs
=> feat: optimise publishing gas costs

.github/workflows/check-move-packages-pull-request.yml, language/move-stdlib/Cargo.toml, language/move-stdlib/src/natives/mod.rs, language/move-stdlib/src/natives/substrate_hash.rs, move-vm-backend-common/src/gas_schedule.rs, move-vm-backend/Cargo.toml, move-vm-backend/tests/assets/move-projects/smove-build-all.sh, move-vm-backend/tests/assets/move-projects/substrate_stdlib_hash/Move.toml, move-vm-backend/tests/assets/move-projects/substrate_stdlib_hash/sources/Scripts.move, move-vm-backend/tests/move_vm.rs
`substrate_hash` is a new module in substrate-stdlib which provides the following functions:
```
native public fun sip_hash(bytes: vector<u8>): u64;
native public fun keccak256(bytes: vector<u8>): vector<u8>;
native public fun sha2_512(bytes: vector<u8>): vector<u8>;
native public fun sha3_512(bytes: vector<u8>): vector<u8>;
native public fun ripemd160(bytes: vector<u8>): vector<u8>;
public fun blake2b_256(bytes: vector<u8>): vector<u8>;
```
=> feat: add native functions for substrate_hash module

move-vm-backend-common/src/abi.rs
- necessary changes for Polkadot-SDK version upgrade
- types in `jsonrpsee` need to implement trait `Clone`
=> feat: implement Clone trait for ModuleAbi
